init, always start lvm after udev now

diff --git a/tools/lib/init.in b/tools/lib/init.in
--- a/tools/lib/init.in
+++ b/tools/lib/init.in
@@ -274,6 +274,26 @@ ListModules() {
   printf "Press <enter> to continue ...\n"
   read a
 }
+do_start_lvm() {
+if [ -f /etc/mdadm.conf ]; then
+
+  [ "$verbose" == "no" ] || printf "mdadm -As...\n"
+  /sbin/mdadm -As
+
+  [ "$verbose" == "no" ] || printf "mdadm --auto-detect...\n"
+  /sbin/mdadm --auto-detect
+fi
+
+### First we activate lvm if possible
+  if [ -f /sbin/lvm ]; then
+    [ "$verbose" == "no" ] || printf "/sbin/lvm vgchange --ignorelockingfailure -ay\n"
+    /sbin/lvm vgchange --ignorelockingfailure -ay
+    if [ $? = 0 ]; then
+       [ "$verbose" == "no" ] || printf "/sbin/lvm vgscan --ignorelockingfailure --mknodes\n"
+       /sbin/lvm vgscan --ignorelockingfailure --mknodes
+    fi
+  fi
+}
 # **********
 # Begin here
 # **********
@@ -320,26 +340,9 @@ done
 if [ -d /lib/modules ] && [ -n "$rootdelay" ] && [ -n "$root" ]; then
         [ "$verbose" == "no" ] || printf "Start udev...\n"
         do_start_udev
+	[ "$verbose" == "no" ] || printf "Start lvm ...\n"
+	do_start_lvm
 fi
-
-if [ -f /etc/mdadm.conf ]; then
-
-  [ "$verbose" == "no" ] || printf "mdadm -As...\n"
-  /sbin/mdadm -As
-
-  [ "$verbose" == "no" ] || printf "mdadm --auto-detect...\n"
-  /sbin/mdadm --auto-detect
-fi  
-
-### First we activate lvm if possible
-  if [ -f /sbin/lvm ]; then
-    [ "$verbose" == "no" ] || printf "/sbin/lvm vgchange --ignorelockingfailure -ay\n"
-    /sbin/lvm vgchange --ignorelockingfailure -ay
-    if [ $? = 0 ]; then
-       [ "$verbose" == "no" ] || printf "/sbin/lvm vgscan --ignorelockingfailure --mknodes\n"
-       /sbin/lvm vgscan --ignorelockingfailure --mknodes
-    fi
-  fi
 
 if [ -n "$rootdelay" ] ; then
 	[ "$verbose" == "no" ] || printf "Wait  %s second(s) ...\n" $rootdelay
@@ -416,6 +419,9 @@ fi
 if [ "$root" == "" ]; then
 	[ "$verbose" == "no" ] || printf "Start udev ...\n"
         do_start_udev
+
+	[ "$verbose" == "no" ] || printf "Start lvm ...\n"
+	do_start_lvm
 
 	[ "$verbose" == "no" ] || printf "Start sysklogd ...\n"
 	do_start_sysklogd
