bugfixes on houaphan, add possibilitÃy to upgrade system at shutdown/reboot

diff --git a/basicfs/rootfs/lib/services/init-functions b/basicfs/rootfs/lib/services/init-functions
--- a/basicfs/rootfs/lib/services/init-functions
+++ b/basicfs/rootfs/lib/services/init-functions
@@ -1193,7 +1193,9 @@ do_stop_mountfs()
   evaluate_retval
 
   # Make sure / is mounted read only (umount bug)
+  log_info_msg "Remonting root file system in read-only mode..."
   mount -o remount,ro /
+  evaluate_retval
 
   # Make all LVM volume groups unavailable, if appropriate
   # This fails if swap or / are on an LVM partition
@@ -1365,6 +1367,164 @@ do_start_sysctl()
     sysctl -q -p
     evaluate_retval
   fi
+}
+################################################################################
+# do_start_network()                                                           #
+#                                                                              #
+# Description: Start the network depending on what's available nothing, wicd   #
+# or networkmanager                                                            #
+#                                                                              #
+################################################################################
+do_config_network()
+{
+NETWORKCONFIG_FILE="/etc/sysconfig/network"
+  if [ ! -f /etc/sysconfig/network ]; then
+    cat > ${NETWORKCONFIG_FILE} << "EOF"
+HOSTNAME='nutyx'
+MANAGER='cli'
+EOF
+fi
+
+# Network configuration
+. ${NETWORKCONFIG_FILE}
+
+NM_PIDFILE="/var/run/NetworkManager.pid"
+WICD_PIDFILE="/var/run/wicd/wicd.pid"
+
+if [ "${MANAGER}" == "" ]; then
+  MANAGER="cli"
+  if [ -f /usr/sbin/NetworkManager ]; then
+     MANAGER="networkmanager"
+  fi
+  if [ -f /usr/bin/wicd ]; then
+     MANAGER="wicd"
+  fi
+fi
+
+}
+do_start_network()
+{
+   do_config_network
+   case "${MANAGER}" in
+      networkmanager)
+         if [ -f /usr/sbin/NetworkManager ]; then
+            if [ ! -d /var/run/NetworkManager ]; then
+               install -d -o root -g root -m 755 /var/run/NetworkManager
+            fi
+            log_info_msg "Starting NetworkManager daemon..."
+            start_daemon /usr/sbin/NetworkManager
+            if [ "${NETWORKWAIT}" == "yes" ]; then
+               [ -z "${LINKDELAY}" ] && LINKDELAY=10
+               log_info_msg "Waiting for network..."
+               nm-online -q --timeout=$LINKDELAY || nm-online -q -x --timeout=30
+               [ "$?" = "0" ] && log_success_msg "Network startup" || log_failure_msg "Network startup"
+               [ -n "${NETWORKDELAY}" ] && /bin/sleep ${NETWORKDELAY}
+            fi
+         else
+            echo "the package networkmanager seems not to be install"
+            echo "check the ${NETWORKCONFIG_FILE} file"
+         fi
+      ;;
+      wicd)
+         if [ -f /usr/bin/wicd ]; then
+            if [ -e $WICD_PIDFILE ]; then
+               echo "Wicd appears to already be running"
+               echo "If this is NOT the case, then remove"
+               echo "$WICD_PIDFILE, check the ${NETWORKCONFIG_FILE} file"
+               echo "and try again"
+            else
+               log_info_msg "Starting the wicd Daemon..."
+               start_daemon /usr/bin/wicd 1>/dev/null
+               evaluate_retval
+               if grep -v ^# /etc/fstab | grep _netdev > /dev/null; then
+                    while ! grep "nameserver" /etc/resolv.conf ;
+                        do
+                            if [ $NETWORKDELAY -gt 0 ]; then
+                               sleep 1
+                               echo -n .
+                               let NETWORKDELAY=$NETWORKDELAY-1
+                               if [ $NETWORKDELAY -lt 1 ]; then
+                                   log_failure_msg2 "Time out"
+                                   exit 1
+                               fi
+                            fi
+                        done
+                        log_success_msg2 "Network successfully configured..."
+               fi
+            fi
+         else
+            echo "the package wicd seems not to be install"
+            echo "check the ${NETWORKCONFIG_FILE} file"
+         fi
+      ;;
+      cli)
+         # Start all network interfaces
+         for file in /etc/sysconfig/ifconfig.*
+         do
+            interface=${file##*/ifconfig.}
+            # Skip if $file is * (because nothing was found)
+            if [ "${interface}" = "*" ]; then
+               continue
+            fi
+            if [ -f /etc/wpa_supplicant.conf.${interface} ] && [ -x /sbin/wpa_supplicant ]; then
+               wpa_supplicant -B -c/etc/wpa_supplicant.conf.${interface} -i${interface} \
+               -P /var/run/wpa_supplicant.${interface}
+               sleep 2
+            fi
+            /sbin/ifup ${interface}
+         done
+      ;;
+   esac
+}
+
+do_stop_network()
+{
+   do_config_network
+   case "${MANAGER}" in
+      networkmanager)
+         if [ -f /usr/sbin/NetworkManager ]; then
+            log_info_msg "Stopping NetworkManager daemon..."
+            killproc /usr/sbin/NetworkManager
+         else
+            echo "the package networkmanager seems not to be install"
+            echo "check the ${NETWORKCONFIG_FILE} file"
+         fi
+      ;;
+      wicd)
+         if [ -e $WICD_PIDFILE ]; then
+            log_info_msg "Stopping the wicd Daemon..."
+            wicd-cli -xyz 1>/dev/null
+            kill $(cat $WICD_PIDFILE)
+            evaluate_retval
+         else
+            echo "wicd appears not to be running..."
+            echo "check the ${NETWORKCONFIG_FILE} file"
+         fi
+      ;;
+      cli)
+         # Reverse list
+         net_files=""
+         for file in  /etc/sysconfig/ifconfig.*
+         do
+             net_files="${file} ${net_files}"
+         done
+
+         # Stop all network interfaces
+         for file in ${net_files}
+         do
+             interface=${file##*/ifconfig.}
+
+             # Skip if $file is * (because nothing was found)
+             if [ "${interface}" = "*" ]; then
+                 continue
+             fi
+             /sbin/ifdown ${interface}
+             if [ -f /var/run/wpa_supplicant.${interface} ]; then
+                 kill `cat /var/run/wpa_supplicant.${interface}`
+             fi
+         done
+      ;;
+   esac
 }
 ################################################################################
 # print_file_system()                                                          #
