install-nutyx
introducing a new variable SHELL. Make install-nutyx possible to choose any shell
when entering or installing NuTyX.

diff --git a/scripts/install-nutyx.in b/scripts/install-nutyx.in
--- a/scripts/install-nutyx.in
+++ b/scripts/install-nutyx.in
@@ -98,7 +98,7 @@ print_error_msg() {
 unmountall() {
 if [ -d "$DEPOT_CD/depot" ]; then
 	umount ${FOLDER}/${DEPOT}
-	umount  `cat /tmp/depot`
+	umount  $(cat /tmp/depot)
 fi
 [ ! -z $MOUNT ] && umount ${FOLDER}/${DEPOT}
 umount ${FOLDER}/run
@@ -135,12 +135,13 @@ echo "
 ******************************
 Chroot path: $DEVICE
 ******************************"
-chroot ${FOLDER} /usr/bin/env -i \
+chroot ${FOLDER} env -i \
 HOME=/root \
+EUID=0 \
 TERM="$TERM" \
 PS1='\u:\w\$ ' \
 $LINUX_ARCH \
-/bin/bash --login
+$SHELL -l
 }
 #******************************************************************************
 # Function - download_pkg()
@@ -181,7 +182,7 @@ download_pkg() {
 #******************************************************************************
 install_pkg() {
 	getPackageFileName ${1}
-	if $TMP/`dirname $PKGADD`/pkginfo -r $FOLDER -i| grep "^$1 " > /dev/null; then
+	if $TMP/$(dirname $PKGADD)/pkginfo -r $FOLDER -i| grep "^$1 " > /dev/null; then
 		boot_mesg "$1 is already install on $DEVICE..."
 		echo_info
 	fi
@@ -230,7 +231,7 @@ end() {
 getPackageFileName() {
 	local BUILD_DATE EXT HEAD
 	if [ ! -f $FOLDER/$DEPOT/$BASE/${1}/.PKGREPO ]; then
-		if ! (`which curl > /dev/null`); then
+		if ! ($(which curl > /dev/null)); then
 			error " Command 'curl' not found, please install curl programm"
 		fi
 		curl -LC - -sS --create-dirs \
@@ -238,13 +239,13 @@ getPackageFileName() {
 		error "Cannot download ${DEPOT_BASE}/${1}/.PKGREPO ..., check URL"
 		chmod -R 755 $FOLDER/$DEPOT
 	fi
-	if [ `wc -l $FOLDER/$DEPOT/$BASE/${1}/.PKGREPO|cut -d " " -f1` -eq 0 ]; then
+	if [ $(wc -l $FOLDER/$DEPOT/$BASE/${1}/.PKGREPO|cut -d " " -f1) -eq 0 ]; then
 		error "${DEPOT_BASE}/${1} not reacheable.."
 	fi
-	HEAD=`head -1 $FOLDER/$DEPOT/$BASE/${1}/.PKGREPO`
+	HEAD=$(head -1 $FOLDER/$DEPOT/$BASE/${1}/.PKGREPO)
 	if [ "${HEAD:10:1}" == "#" ]; then
-		BUILD_DATE="`echo $HEAD|cut -d "#" -f1`"
-		EXT="`echo $HEAD|cut -d "#" -f2`"
+		BUILD_DATE="$(echo $HEAD|cut -d "#" -f1)"
+		EXT="$(echo $HEAD|cut -d "#" -f2)"
 		PackageFileName="${1}${BUILD_DATE}${ARCH}${EXT}"
 	fi
 }
@@ -298,7 +299,7 @@ NORMAL="\[\e[0m\]"
 RED="\[\e[1;31m\]"
 GREEN="\[\e[1;32m\]"
 WHITE="\[\e[1;37m\]"
-INFOMACHINE="`date +%H:%M` `uname -m` `uname -r` `whoami`@`uname -n`"
+INFOMACHINE="$(date +%H:%M) $(uname -m) $(uname -r) $(whoami)@$(uname -n)"
 prompt_command() {
 # Sauvegarde de la pos courante
 tput sc
@@ -320,12 +321,8 @@ echo -n "]"
 # Remet le curseur à sa place
 tput rc
 }
-EOF
+PROMPT_COMMAND=prompt_command
 
-[ "$INIT" = "sysd" ] || echo "PROMPT_COMMAND=prompt_command" >> \
-${FOLDER}/etc/$FILE
-
-cat >> ${FOLDER}/etc/$FILE << "EOF"
 case $TERM in
         xterm|rxvt*)
                 TITLEBAR='\[\033]0;\u@\h \007\]'
@@ -649,11 +646,8 @@ if [ -f /etc/${INSTALL_COMMAND}.conf.d/$FILE ]; then
 fi
 cat > ${FOLDER}/etc/$FILE << "EOF"
 # Begin /etc/shells
-
 /bin/sh
 /bin/bash
-
-# End /etc/shells
 EOF
 }
 generate_umask_sh() {
@@ -794,7 +788,7 @@ pathappend () {
         export $PATHVARIABLE="${!PATHVARIABLE:+${!PATHVARIABLE}:}$1"
 }
 
-export -f pathremove pathprepend pathappend
+[ "$SHELL" == "/bin/bash" ] &&  export -f pathremove pathprepend pathappend
 
 # Set the initial path
 export PATH=/usr/bin:/bin:/usr/sbin:/sbin
@@ -1032,72 +1026,12 @@ fi
 echo "
 # Default server URL
 url ${URL}
-#" > ${FOLDER}/etc/cards.conf
-[ "$INIT" = "sysd" ] || echo "
 #
-## For all the main desktops
+## For all the main desktops (KDE,XFCE,LXDE,MATE)
 # Comment following line
-# If you don't want to install any main desktop
+# If you don't want to install any of those interfaces
 #
 dir ${DEPOT}/desktops
-#" >> ${FOLDER}/etc/cards.conf
-[ "$INIT" = "sysd" ] && echo "
-## For nos
-# Comment following line
-# If you don't want to install Non Open source/Not compiled packages
-#
-dir /var/lib/pkg/depot/nos
-#
-## For community
-# Uncomment following line if you want community packages
-# dir /var/lib/pkg/depot/community-extra
-# dir /var/lib/pkg/depot/community
-#
-## For LXQt
-# Uncomment following 2 lines
-# if you want to install LXQt when available
-#
-# dir /var/lib/pkg/depot/lxqt-extra
-# dir /var/lib/pkg/depot/lxqt
-#
-## For lxde
-# Comment following 2 lines
-# if you don't want to install lxde
-#
-dir /var/lib/pkg/depot/lxde-extra
-dir /var/lib/pkg/depot/lxde
-#
-## For Gnome
-# Comment following 2 lines
-# if you don't want to install gnome
-#
-dir /var/lib/pkg/depot/gnome-extra
-dir /var/lib/pkg/depot/gnome
-#
-## For mate
-# Comment following 2 lines
-# if you don't want to install mate
-#
-dir /var/lib/pkg/depot/mate-extra
-dir /var/lib/pkg/depot/mate
-#
-## For kde5
-# Comment following 2 lines
-# if you don't want to install kde5
-#
-dir /var/lib/pkg/depot/kde5-extra
-dir /var/lib/pkg/depot/kde5
-#
-## For xfce4
-# Comment following 2 lines
-# if you don't want to install xfce4
-#
-dir /var/lib/pkg/depot/xfce4-extra
-dir /var/lib/pkg/depot/xfce4
-#" >> ${FOLDER}/etc/cards.conf
-echo "
-## Normally everything under this line
-# are needed stuffs
 #
 ## For all the graphical applications
 dir ${DEPOT}/gui-extra
@@ -1179,11 +1113,10 @@ fi
 
 [ -z "$VERSION" ] && VERSION="rolling"
 if [ "$VERSION" == "development" ]; then
-	CODE_NAME="`date +%Y%m%d`"
+	CODE_NAME="$(date +%Y%m%d)"
 else
 	CODE_NAME="Houaphan"
 fi
-[ "$VERSION" = "sysd" ] && INIT="sysd"
 
 [ -z "$DEPOT" ] && DEPOT="/var/lib/pkg/depot"
 [ -z "$FOLDER" ] && FOLDER="/mnt/hd"
@@ -1200,25 +1133,15 @@ bc less"
 fi
 [ -z $KERNEL ] && CORE="-n $CORE"
 
-[[ ! -z "$KERNEL" && -z "$INIT" ]] && INIT="sysv"
-
-[ "$INIT" = "sysv" ] && INITS="eudev sysklogd sysvinit dbus systemd runyx"
-if [ "$INIT" = "sysd" ]; then
-	INITS="dbus systemd"
-	CORE+=" libcap kmod"
-	CHROOT_LIST+=" nettle gnutls p11-kit libtasn1 libffi util-linux"
-fi
-[ "$INIT" = "runyx" ] && INITS="eudev sysklogd runyx"
+INITS="eudev sysklogd sysvinit dbus systemd runyx"
 
 [ "$KERNEL" = "NONE" ] && unset KERNEL
 [ "$KERNEL" = "none" ] && unset KERNEL
 
 
 if [ ! -z "$KERNEL" ]; then
-	[ "$INIT" != "sysd" ] && \
-	  CORE+=" libcap util-linux kmod"
-
-	CORE+=" kbd pam \
+	CORE+=" libcap util-linux \
+kmod kbd pam \
 gdbm e2fsprogs libpipeline \
 gettext procps-ng \
 psmisc sudo tzdata \
@@ -1243,11 +1166,18 @@ LOCAL_DEPOT_PACKAGES="$DEPOT/$BASE"
 DEPOT_CD="/media/cdrom"
 
 SETUP_FILE=/tmp/setup
-
+if [ "$SHELL" == "/bin/bash" ]; then
+  if [ -f $LFS/bin/ash ]; then
+	SHELL=/bin/ash
+  fi
+  if [ -f $LFS/bin/bash ]; then
+	SHELL=/bin/bash
+  fi
+fi
 }
 config() {
-HOST_ARCH=`uname -m`
-[ -z "$ARCH" ] && ARCH=`uname -m`
+HOST_ARCH=$(uname -m)
+[ -z "$ARCH" ] && ARCH=$(uname -m)
 [ "$ARCH" = "i686" -a "$HOST_ARCH" = "x86_64" ] && LINUX_ARCH="linux32" || LINUX_ARCH=""
 
 # Number of seconds between STOPSIG and FALLBACK when stopping processes
@@ -1272,9 +1202,9 @@ WCOL=$((${COL} - 2))
 
 ## Provide an echo that supports -e and -n
 # If formatting is needed, $ECHO should be used
-case "`echo -e -n test`" in
+case "$(echo -e -n test)" in
         -[en]*)
-                ECHO=/bin/echo
+                ECHO=$(which echo)
                 ;;
         *)
                 ECHO=echo
@@ -1354,13 +1284,13 @@ mknod -m 600 ${FOLDER}/dev/console c 5 1
 mknod -m 666 ${FOLDER}/dev/null c 1 3
 }
 download_pkgadd() {
-	PKGADD="`which pkgadd`"
+	PKGADD="$(which pkgadd)"
 	if [ "$PKGADD" != "" ];then
-		mkdir -p $TMP/`dirname $PKGADD`
-		cp  $PKGADD $TMP/`dirname $PKGADD`/
-		ln -s $TMP/`dirname $PKGADD`/pkgadd  $TMP/`dirname $PKGADD`/pkginfo
+		mkdir -p $TMP/$(dirname $PKGADD)
+		cp  $PKGADD $TMP/$(dirname $PKGADD)/
+		ln -s $TMP/$(dirname $PKGADD)/pkgadd  $TMP/$(dirname $PKGADD)/pkginfo
 	else
-		if ! (`which bsdtar > /dev/null`); then
+		if ! ($(which bsdtar > /dev/null)); then
 			error " Command 'bsdtar' not found, please install libarchive"
 		fi
 
@@ -1387,11 +1317,9 @@ check_mountfolder() {
 }
 generate_setupfile() {
 if [[ -z "$INITS" && -z "$CORE" && -z "$DEVEL" ]];then
-	echo "#!/bin/bash
-exit" > $FOLDER/$SETUP_FILE
+	echo "exit" > $FOLDER/$SETUP_FILE
 else
-	echo "#!/bin/bash
-source /etc/profile
+	echo "source /etc/profile
 cards sync
 cards install $CORE \
 $INITS \
@@ -1400,7 +1328,7 @@ exit" > $FOLDER/$SETUP_FILE
 fi
 chmod 177 $FOLDER/$SETUP_FILE
 setup_chroot
-chroot ${FOLDER} /usr/bin/env $LINUX_ARCH /bin/bash -c "$SETUP_FILE"
+chroot ${FOLDER} env $LINUX_ARCH "$SHELL" -c "$SETUP_FILE"
 unmountall
 }
 install_configuration_files() {
@@ -1457,7 +1385,6 @@ parse_options() {
 				unmountall
 				exit 0;;
 			-ic|--install-config)
-				check_variables
 				check_lfs "$@"
 				check_root
 				check_mountfolder
@@ -1467,7 +1394,7 @@ parse_options() {
 				install_configuration_files
 				exit 0;;
 			-v|--version)
-				echo "`basename $INSTALL_COMMAND` #VERSION#-$RELEASE"
+				echo "$(basename $INSTALL_COMMAND) #VERSION#-$RELEASE"
 				exit 0;;
 			/*)
 				boot_mesg "
@@ -1475,7 +1402,7 @@ parse_options() {
 "
 				exit 1;;
 			*)
-				echo "`basename $0`: invalid option $1"
+				echo "$(basename $0): invalid option $1"
 				exit 1 ;;
 		esac
 		shift
@@ -1483,8 +1410,8 @@ parse_options() {
 }
 main() {
 	config
-	if [ -f /etc/`basename $INSTALL_COMMAND`.conf ]; then
-		source /etc/`basename $INSTALL_COMMAND`.conf
+	if [ -f /etc/$(basename $INSTALL_COMMAND).conf ]; then
+		source /etc/$(basename $INSTALL_COMMAND).conf
 	fi
 	check_variables  "$@"
 	parse_options "$@"
@@ -1500,11 +1427,12 @@ KERNEL     : $KERNEL
 DEPOT      : $DEPOT
 MOUNT      : $MOUNT
 FOLDER     : $FOLDER
+SHELL      : $SHELL
 DEPOT_BASE : $DEPOT_BASE
 DEVEL      : $DEVEL
 CHROOT_LIST: $CHROOT_LIST"
 	check_root
-	TMP=`mktemp -d`
+	TMP=$(mktemp -d)
 	check_mountfolder
 	check_mountpoint
 
@@ -1525,5 +1453,5 @@ CHROOT_LIST: $CHROOT_LIST"
 
 readonly BASE="base"
 readonly RELEASE=1
-INSTALL_COMMAND="`basename $0`"
+INSTALL_COMMAND="$(basename $0)"
 main "$@"
